apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings
  namespace: default
data:
  appSettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "AzureAd": {
        "Instance": "https://login.microsoftonline.com",
        "ClientId": "$($AAD_APP_ID)",
        "TenantId": "$($AAD_TENANT)"
      }
    }
