apiVersion: v1
kind: ServiceAccount
metadata:
  name: client.app1
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-client
  labels:
    app: api-client
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: api-client
        service: webapp
    spec:
      containers:
        - name: api-client
          image: $($ACR)/webclientapp:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
          volumeMounts:
          - name: token-vol
            mountPath: /service-account
            readOnly: true
          - name: appsettings-volume
            mountPath: /app/settings            
      imagePullSecrets:
        - name: acr-secret         
      serviceAccountName: $($SERVICE_ACCOUNT)
      volumes:
      - name: token-vol
        projected:
          sources:
          - serviceAccountToken:
              audience: "api://AzureADTokenExchange"
              expirationSeconds: 3600
              path: token
      - name: appsettings-volume
        configMap:
          name: appsettings
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: api-client
    service: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 4080
      targetPort: 80
      protocol: TCP
  selector:
    service: webapp