apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-client
  labels:
    app: api-client  
spec:
  replicas: 1    
  selector:
    matchLabels:
      service: webapp 
  template:
    metadata:
      labels:
        app: api-client
        service: webapp        
    spec:
      containers:
        - name: api-client
          image: $($IMAGE)
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
          volumeMounts:
          - name: token-vol
            mountPath: "/service-account"
            readOnly: true
          - name: appsettings-volume
            mountPath: /app/settings                
      serviceAccountName: $($SERVICE_ACCOUNT)
      volumes:
      - name: token-vol
        projected:
          sources:
          - serviceAccountToken:
              audience: "api://AzureADTokenExchange"
              expirationSeconds: 3600
              path: token
      - name: appsettings-volume
        configMap:
          name: appsettings              
