apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-12-19T22:26:57Z"
  name: client.app1
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-client
spec:
  selector:
    matchLabels:
      run: api-client
  replicas: 1      
  template:
    metadata:
      labels:
        run: api-client
    spec:
      containers:
        - name: api-client
          image: webclientapp:latest
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
          volumeMounts:
          - name: token-vol
            mountPath: "/service-account"
            readOnly: true
      serviceAccountName: client.app1
      volumes:
      - name: token-vol
        projected:
          sources:
          - serviceAccountToken:
              audience: "api://AzureADTokenExchange"
              expirationSeconds: 3600
              path: token
---
apiVersion: v1
kind: Service
metadata:
  name: api-client
  labels:
    run: api-client
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: api-client