apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: api-client
    service: webapp
spec:
  type: NodePort
  ports:
    - port: 4080
      nodeport: 30008
  selector:
    service: webapp