apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: api-client
    service: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 4080
      targetPort: 80
      protocol: TCP
  selector:
    service: webapp