apiVersion: v1
kind: ConfigMap
metadata:
  name: mtrest-config
  namespace: default
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a configmap Index file </h1>
    </html