apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  labels:
    app: mtrest
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapi
  template:
    metadata:
      labels:
        app: mtrest
        service: webapi
    spec:
      containers:
        - name: webapi
          image: localhost:5000/restfunctions:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:443
